name: "journeyplanner"

services:
  db:
    image: mariadb:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PW
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD

volumes:
  dbdata:
