# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend/" # Location of package manifests
    open-pull-requests-limit: 100
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Vienna"
    commit-message:
      # Prefix all commit messages with "build(deps): "
      prefix: "build(deps)"
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/backend/" # Location of package manifests
    open-pull-requests-limit: 100
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Vienna"
    commit-message:
      # Prefix all commit messages with "build(deps): "
      prefix: "build(deps)"
