pipeline {
    agent none 
    environment {
        FRONTEND_IMAGE = 'journeyplanner/frontend:latest'
        FRONTEND_INFISICAL_API_URL = credentials('frontend_infisical_api_url')
        FRONTEND_INFISICAL_TOKEN = credentials('frontend_infisical_token')
    }
    stages {
        stage('Check Frontend Code') {
            agent {
                docker { 
                    image 'node:24' 
                    args '-u root:root' 
                }
            }
            steps {
                dir('frontend') {
                    sh 'CI=true npm ci'
                    sh 'npx prettier . --check'
                    sh 'npx eslint .'
                }
            }
        }
        stage('Build Docker Image') {
            agent {
                label 'docker' 
            }
            steps {
                dir('frontend') {
                    sh """
                    docker build -t ${env.FRONTEND_IMAGE} \
                      --build-arg INFISICAL_API_URL=${FRONTEND_INFISICAL_API_URL} \
                      --build-arg INFISICAL_TOKEN=${FRONTEND_INFISICAL_TOKEN} .
                    """
                }
            }
        }
    }
}
