pipeline {
    agent any
    environment {
        FRONTEND_IMAGE = 'journeyplanner/frontend:latest'
        FRONTEND_INFISICAL_API_URL = credentials('frontend_infisical_api_url')
        FRONTEND_INFISICAL_TOKEN = credentials('frontend_infisical_token')
    }
    stages {
        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    script {
                        docker.build(env.FRONTEND_IMAGE, '--build-arg INFISICAL_API_URL=${FRONTEND_INFISICAL_API_URL} --build-arg INFISICAL_TOKEN=${FRONTEND_INFISICAL_TOKEN} .')
                    }
                }
            }
        }
        stage('Check Frontend Code') {
            steps {
                dir('frontend') {
                    script {
                        sh 'npm install'
                        sh 'npx prettier . --check'
                        sh 'npx eslint .'
                    }
                }
            }
        }
    }
}
