pipeline {
    agent none
    environment {
        BACKEND_IMAGE = 'journeyplanner/backend:latest'
    }
    stages {
        stage('Check Backend Code') {
            agent {
                docker { 
                    image 'node:24'
                    args '-u root:root' 
                }
            }
            steps {
                dir('backend') {
                    sh 'CI=true npm ci' 
                    sh 'npx prettier . --check'
                }
            }
        }
        stage('Build Backend Image') {
            agent {
                label 'docker' 
            }
            steps {
                dir('backend') {
                    sh "docker build -t ${env.BACKEND_IMAGE} ."
                }
            }
        }
    }
}
