pipeline {
    agent any
    environment {
        BACKEND_IMAGE = 'journeyplanner/backend:latest'
    }
    stages {
        stage('Build Backend') {
            steps {
                dir('backend') {
                    script {
                        docker.build(env.BACKEND_IMAGE)
                    }
                }
            }
        }
        stage('Check Backend Code') {
            agent { docker { image 'composer:lts' } }
            steps {
                dir('backend') {
                    script {
                        sh 'composer install'
                        sh './vendor/bin/pint --test'
                    }
                }
            }
        }
    }
}
