name: "journeyplanner"

services:
  web:
    image: nginx:stable-alpine
    ports:
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/certs:/etc/nginx/certs
    restart: always
    depends_on:
      - frontend
  frontend:
    image: registry.journeyplanner.io/journeyplanner/frontend:latest
    restart: always
    env_file:
      - stack.env
    depends_on:
      - backend
      - i18n
  i18n:
    image: registry.journeyplanner.io/journeyplanner/i18n:latest
    restart: always
    env_file:
      - stack.env
  backend:
    image: registry.journeyplanner.io/journeyplanner/backend:latest
    restart: always
    env_file:
      - stack.env
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - stack.env

volumes:
  dbdata:
