name: "journeyplanner"

services:
  web:
    image: nginx:stable-alpine
    pull_policy: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/well-known:/usr/share/nginx/html/.well-known
      - /home/ubuntu/jp/certs:/etc/nginx/certs
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    depends_on:
      - frontend
  frontend:
    build:
      context: ../frontend
      args:
        - INFISICAL_API_URL=$FRONTEND_INFISICAL_API_URL
        - INFISICAL_TOKEN=$FRONTEND_INFISICAL_TOKEN
    pull_policy: build
    restart: unless-stopped
    depends_on:
      - backend
      - i18n
  i18n:
    build: ./i18n
    pull_policy: build
    restart: unless-stopped
    volumes:
      - i18n:/app/i18n
    environment:
      - TOLGEE_API_KEY=$TOLGEE_API_KEY
      - TOLGEE_PROJECT_ID=$TOLGEE_PROJECT_ID
      - TOLGEE_API_URL=$TOLGEE_API_URL
  backend:
    build: ../backend
    pull_policy: build
    restart: unless-stopped
    environment:
      - INFISICAL_API_URL=$BACKEND_INFISICAL_API_URL
      - INFISICAL_TOKEN=$BACKEND_INFISICAL_TOKEN
    depends_on:
      - db
      - tusd
    volumes:
      - uploads:/tusd-data
      - journey_media:/app/storage/app/journey_media
      - business_images:/app/storage/app/business_images
  db:
    image: mariadb:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
  tusd:
    image: tusproject/tusd:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - uploads:/tusd-data
    command: -hooks-http http://backend:80/api/upload -hooks-http-forward-headers Authorization -hooks-enabled-events pre-create,post-finish -behind-proxy -upload-dir /tusd-data -max-size 1000000000

volumes:
  dbdata:
  uploads:
  journey_media:
  business_images:
  i18n:
