name: "journeyplanner"

services:
  web:
    image: nginx:stable-alpine
    pull_policy: always
    ports:
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/jp/certs:/etc/nginx/certs
    restart: unless-stopped
    depends_on:
      - frontend
  frontend:
    build:
      context: ../frontend
      args:
        - INFISICAL_API_URL=$FRONTEND_INFISICAL_API_URL
        - INFISICAL_TOKEN=$FRONTEND_INFISICAL_TOKEN
    pull_policy: build
    restart: unless-stopped
    depends_on:
      - backend
      - i18n
  i18n:
    build: ./i18n
    pull_policy: build
    restart: unless-stopped
    volumes:
      - i18n:/app/i18n
    environment:
      - TOLGEE_API_KEY=$TOLGEE_API_KEY
      - TOLGEE_PROJECT_ID=$TOLGEE_PROJECT_ID
      - TOLGEE_API_URL=$TOLGEE_API_URL
  backend:
    build: ../backend
    pull_policy: build
    restart: unless-stopped
    environment:
      - INFISICAL_API_URL=$BACKEND_INFISICAL_API_URL
      - INFISICAL_TOKEN=$BACKEND_INFISICAL_TOKEN
  db:
    image: mariadb:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD

volumes:
  dbdata:
  i18n:
