name: "journeyplanner"
version: "3.8"

services:
  web:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - frontend
  frontend:
    build: ../frontend
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
      - i18n
  i18n:
    build: ./i18n
    restart: always
    env_file:
      - .env
  backend:
    build: ../backend
    restart: always
    env_file:
      - .env
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env

volumes:
  dbdata:
